// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX37S1g_Eo7eZZZGlzKVN71aMZxLmXpkM',
    appId: '1:861779122333:web:4baf56e7f2a733ec679c74',
    messagingSenderId: '861779122333',
    projectId: 'chapchapapp-fa630',
    authDomain: 'chapchapapp-fa630.firebaseapp.com',
    storageBucket: 'chapchapapp-fa630.appspot.com',
    measurementId: 'G-JZZ12G8V6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGhsmVOqAL6NDyx4aZm1QHIRURrwUmvDg',
    appId: '1:861779122333:android:371c4bd13350821e679c74',
    messagingSenderId: '861779122333',
    projectId: 'chapchapapp-fa630',
    storageBucket: 'chapchapapp-fa630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMwTWEbB6hHnBhY1gJJYfYSr1pu-siOfc',
    appId: '1:861779122333:ios:d7a7d49c0116b6a3679c74',
    messagingSenderId: '861779122333',
    projectId: 'chapchapapp-fa630',
    storageBucket: 'chapchapapp-fa630.appspot.com',
    iosBundleId: 'com.wizmea.chapchapApp',
  );
}
